### ISSUE TITLE
Cool! but how to run Telescope with it ?

### ISSUE THREAD

**Issue by tvvocold** [tutaslabs/openshift-meteor#1]
https://github.com/TelescopeJS/Telescope

**Comment by tvvocold** [comment]
I had followed ur step in http://www.tutas-labs.com/deploying-meteor-applications-to-openshift-paas/ 
in step 7  i  

```
$git clone https://github.com/TelescopeJS/Telescope
$meteor build bundle& cd bundle& cp Telescope.tar.gz to diy folder.
but when i run $tar -xvf Telescope.tar.gz -s '/^bundle//'
it shows "tar: /^bundle: Not found in archive"
i think it maybe i use windows?anyway i just untar it with winrar and put the bundle file in diy folder.
```

after git add ,commit and push ,finally i got 

> "Half way there! - Next Steps…
> Create a Meteor.js example project" 

in my domian page.
So what's wrong with my step and how to fix?

Updates:
i just check the https://github.com/vladka/openshift-meteor-leaderboard-customNode and find the bundle folder shoudn't in bundle folder , so i cd bundle &cp \* ../ and git push then i got 503 error in site.
and here is the [log](http://p.fdzh.org/paste/qALnp5Ek)

**Comment by tutaslabs** [comment]
Ray,

I’ll look at this weekend. You shouldn’t be running any commands by hand other than the push.sh script. It does all the building and taring and un-taring for you.
The meteor build command creates a ‘bundle’ root folder which messes up the push to open shift. That’s why it gets stripped ( -s) when un-taring to the push directory. 
Something may have changed with the latest release of meteor 1.0.3.  I’ll look.

thanks

**Comment by tvvocold** [comment]
That would be nice!
BTW, Send me updates, plz!

**Comment by tutaslabs** [comment]
Ray was trying to deploy this from a Windows system which is not supported by Meteor. Meteor uses Linux/Unix style file names that are incompatible with Windows.
