### ISSUE TITLE
The performance

### ISSUE THREAD

**Issue by tvvocold** [tutaslabs/openshift-meteor#2]
Telescope is very slow in one gears, how to improve it with vladka' Scalable solution?(mogondb has own gear)

like 

```
$rhc app-create scableapp diy-0.1 --from-code https://github.com/tutaslabs/openshift-meteor-telescope 
$rhc cartridge-add mongodb-2.4 cron-1.4 -a scableapp
$rhc scale-cartridge diy-0.1 -a myapp --min 1 --max 2
```

right?

**Comment by tutaslabs** [comment]
Don’t know why it would be slow. Doubt it’s mongo. I have commercial apps running on open shift with 10’s of thousands of records.

the mongo connection is just a URL defined in the environment so i can be anywhere, even on another gear i suppose. 
the meteorshim file defines the open shift environment variables.

Strange. I don’t find my install to be overly slow. then again i only have the installed posts… nothing added.
